version: "3.7"
services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: camunda-api
    environment:
      - SWAGGER_JSON=/camunda/openapi.json
    volumes:
      - ./:/camunda
    ports:
      - 88:8080
